# Generated by Django 5.1 on 2024-09-02 05:59

from django.db import migrations

def populate_estado_pedido(apps, schema_editor):
    EstadoPedido = apps.get_model('LaEsquina', 'EstadoPedido')
    EstadoPedido.objects.create(nombre_estado='En Proceso')
    EstadoPedido.objects.create(nombre_estado='Completado')

class Migration(migrations.Migration):

    dependencies = [
        ('LaEsquina', '0001_initial'),  # Ajusta esto al número correcto de tu migración inicial
    ]

    operations = [
        migrations.RunPython(populate_estado_pedido),
    ]
