# Generated by Django 5.1 on 2024-09-02 06:18

from django.db import migrations

def update_estado_pedido(apps, schema_editor):
    EstadoPedido = apps.get_model('LaEsquina', 'EstadoPedido')
    # Encuentra el estado con nombre 'EnProceso' y actualízalo
    EstadoPedido.objects.create(nombre_estado='Sin completar')
    estado = EstadoPedido.objects.get(nombre_estado='EnProceso')
    estado.nombre_estado = 'En Proceso'
    estado.save()

class Migration(migrations.Migration):

    dependencies = [
        ('LaEsquina', '0002_auto_20240901_2359'),  # Ajusta esto al número correcto de tu migración anterior
    ]

    operations = [
        migrations.RunPython(update_estado_pedido),
    ]
