# Generated by Django 5.1 on 2024-09-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaEsquina', '0006_auto_insert_datos_admin_aseguradora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/'),
        ),
    ]
