# Generated by Django 5.1 on 2024-09-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaEsquina', '0008_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]