# Generated by Django 5.1 on 2024-11-06 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaEsquina', '0011_auto_20241030_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(limit_choices_to={'id_rol': 2}, on_delete=django.db.models.deletion.CASCADE, to='LaEsquina.usuario')),
            ],
        ),
    ]
