# Generated by Django 5.1 on 2024-11-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaEsquina', '0012_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoservicio',
            name='direccion_servicio',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoservicio',
            name='hora_servicio',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
